# Этап 1: Установка зависимостей и загрузка данных NLTK
FROM python:3.11.8-slim-bookworm as builder

# Установка системных зависимостей
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    python3-dev \
    unzip \  
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Создание виртуального окружения
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Установка Python-зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Загрузка данных NLTK
RUN python -m nltk.downloader stopwords punkt  # Основные данные для работы
RUN mkdir -p /opt/nltk_data && mv /root/nltk_data/* /opt/nltk_data/

# -----------------------------------------------------------
# Этап 2: Финальный образ
FROM python:3.11.8-slim-bookworm

# Настройка переменной окружения для NLTK
ENV NLTK_DATA=/opt/nltk_data

# Создание пользователя и рабочих директорий
RUN useradd -m appuser && mkdir -p /app && chown -R appuser:appuser /app
USER appuser
WORKDIR /app

# Копирование виртуального окружения и данных NLTK
COPY --from=builder --chown=appuser:appuser /opt/venv /opt/venv
COPY --from=builder --chown=appuser:appuser /opt/nltk_data /opt/nltk_data

# Копирование исходного кода
COPY --chown=appuser:appuser ./app .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]