model:
  name: "bert-base-uncased"
  task_type: "binary"

training:
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  num_train_epochs: 5
  learning_rate: 2e-5
  warmup_steps: 500
  weight_decay: 0.01
  logging_steps: 100
  eval_strategy: "epoch"
  save_strategy: "epoch"
  load_best_model_at_end: True
  metric_for_best_model: "eval_f1"
  greater_is_better: True